### ISSUE TITLE
Touhou 18 demo is out!!! :Pog:

### ISSUE THREAD

**Issue by toimine** [ack7139/thprac#16]
Time to add thprac support!!!!!!
(if you've got the game on reitaisai or, ahem, other places)

**Comment by ack7139** [comment]
Unfortunately, there's no plan for adding th18tr support, because:
1. There's way too much stuff waiting to be added right now.
2. Almost non of the (th18tr supporting) code can be re-used for the release version of the game, which is planned to release at the beginning of May, giving it merely a month or so to be anything useful.
3. Priw8 has already made a practice patch, and there's no reason not to just use that.
